### ISSUE TITLE
Falsey resolve methods

### ISSUE THREAD

**Issue by jiricrispeyn** [sentiance/react-native-sentiance#117]
Some of the bridged methods resolve a promise with a falsey value (e.g. `resolve(nil)`).
While we are technically resolving the promise correctly, it could introduce some unexpected behaviour on the JS side.

```
const reset = async () => {
  return await RNSentiance.reset();
}

const hasReset = reset();

if (hasReset) {
  // code will not be executed since resolve was falsey
}
```

I know this is relatively easy to tackle this in a way that it will work as expected. But above code snippet is a commonly used approach.

An improvement could be to refactor the resolves so that they return a truthy value.

**Comment by countcain** [comment]
this is solved.
