### ISSUE TITLE
[Manual Install] Where can I find SENTTransportDetectionSDK.framework?

### ISSUE THREAD

**Issue by harrisrobin** [sentiance/react-native-sentiance#24]
In your readme, the following step says: 

> In XCode, in the project navigator, select RNSentianceLibrary.xcodeproj. Add the folder where SENTTransportDetectionSDK.framework is located to Search Paths ➜ Framework Search Paths

However, I am unable to find `SENTTransportDetectionSDK.framework`. I would be more than happy to update the readme with the appropriate information, also found another thing that's out of date in there. Any help would be much appreciated :)

**Comment by jiricrispeyn** [comment]
I have updated the README with information on where `SENTSDK.framework` can be downloaded from (also, `SENTTransportDetectionSDK.framework` was renamed to `SENTSDK.framework` since last major version update).

Thanks, @harrisrobin !
