### ISSUE TITLE
[Android] Failed to resolve: com.sentiance:sdk:4.4.0-R

### ISSUE THREAD

**Issue by harrisrobin** [sentiance/react-native-sentiance#39]
![image](https://user-images.githubusercontent.com/3880008/52767808-908c8080-2ff9-11e9-9630-6e347f8d5b82.png)

Running into this issue when trying to build the android app for the first time. Maybe i'm missing a step? How i choose worldDebugApiElements config?

Thanks in advance :)

## EDIT

Removing 
https://github.com/sentiance/react-native-sentiance/blob/9df5e56af96ed61e044be900ca7c3becaff03c61/android/build.gradle#L33-L35

AND

https://github.com/sentiance/react-native-sentiance/blob/9df5e56af96ed61e044be900ca7c3becaff03c61/android/build.gradle#L50-L53

Gets me past this step, however i now run into this: 
![image](https://user-images.githubusercontent.com/3880008/52768571-e2360a80-2ffb-11e9-97e6-5d94cd73a94e.png)

Unfortunately my Android/Java knowledge is pretty limited so can't really submit a fix other than modifying it locally in node_modules.

**Comment by robonaut** [comment]
Can you try to do the following?

Add following entry to `android/build.gradle` 
```
    allprojects {
      repositories {
        ...
        maven {
            url "http://repository.sentiance.com"
        }
      }
    }
```

I will update the README accordingly.

**Comment by harrisrobin** [comment]
@robonaut after updating RNsentiance to the latest version (2.0.0) and adding the repository url to `android/build.gradle`, still no luck unfortunately:
<img width="870" alt="screen shot 2019-02-26 at 11 18 44 am" src="https://user-images.githubusercontent.com/3880008/53428197-5dae9900-39b8-11e9-87ae-455ee729037f.png">


Anything else you think I should try?

**Comment by robonaut** [comment]
It seems that we have to define the correct configuration here. 

Can you try to add  `missingDimensionStrategy "sdkVersion", "world"` to the defaultConfig section  in your app/build.gradle?

Thanks!
